name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          build_dir: build
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
